changelog.go
changelog_test.go
releaserpleaser.go
updater.go
updater_test.go

Mvoe the handling of `Changelog.md` to use the `Updater` interface introduced in #14.

refactor: move changelog file to updater interface

---

.github/workflows/release.yaml

Current permissions are not sufficient and fail with:
>  Error: failed to publish images: error publishing ko://github.com/apricote/releaser-pleaser/cmd/rp: writing sbom: POST https://ghcr.io/v2/apricote/releaser-pleaser/blobs/uploads/: DENIED: installation not allowed to Write organization package

fix(ci): ko pipeline permissions

---

.github/workflows/releaser-pleaser.yaml

The previous job always used the last release version of releaser-pleaser. This caused two issues:
- if new flags were added to `action.yml` since the last release, the program errored because the flags are unknown.
- right after merging a release pr, the image reference was already updated, but no new container image was built yet.
This fixes both issues, by using a locally built version of releaser-pleaser, which is always up-to-date and available.
Fixes #20

ci: use current code for releaser-pleaser action

---

.github/workflows/releaser-pleaser.yaml

With `pull_request`, we run in the context of the pull request branch.
- This means we run with the code from the PR branch, possibly breaking the current release PR for this repo with in-progress, unreviewed changes.
- This means that the secret is not available on Pull Requests from forks.
Switching to `pull_request_target` means we always run in the scope of the original repository. The secret is available and the code is checked out from our main branch.
`pull_request_target` has security considerations, but they do not apply here as we do not check out or run code from the (external, malicious) PR.

ci: run on pr updates from main branch

---

releasepr.go
releaserpleaser.go

Right now we always show all new releasable commits since the last _stable_ release.
If a project publishes multiple pre-releases in a row, they all repeat the same lines with a few new additions.
On the other hand, when we cut a stable release, we do want to show all changes since the last stable release, as we can not expect users to read the changelog of pre-releases.
As a compromise, the code now looks at the type of release that is being created, and decides based on that if we will look at STABLE..HEAD (stable release) or LATEST..HEAD (pre-release).
Close #33

feat: less repetitive entries for for prerelease changelogs

---

internal/markdown/extensions/ast/section.go
internal/markdown/extensions/section.go
internal/markdown/goldmark.go
internal/markdown/goldmark_test.go
internal/releasepr/releasepr.go
internal/releasepr/releasepr_test.go

- Move all Markdown parsing and formatting to `internal/markdown`
- Add tests for `ReleasePullRequest.ChangelogText()`

refactor: releasepr markdown handling

---

docs/guides/release-notes-rp-commits-release-pr.png
docs/guides/release-notes-rp-commits.png
docs/guides/release-notes.md
docs/reference/pr-options.md
internal/forge/github/github.go
internal/markdown/goldmark.go
internal/markdown/goldmark_test.go
internal/releasepr/releasepr.go
internal/releasepr/releasepr_test.go
prbody.go
prbody_test.go
releaserpleaser.go

feat: edit commit message after merging through PR

---

internal/forge/forge.go
internal/forge/github/github.go
releaserpleaser.go

Makes navigating to the PR way easier when looking at the logs.
This requires a new `Forge.PullRequestURL()` method that needs to be implemented for all forges.

feat(cli): show release PR url in log messages

---

cmd/rp/cmd/run.go
internal/commitparser/conventionalcommits/conventionalcommits.go
internal/commitparser/conventionalcommits/conventionalcommits_test.go

We should not fail the whole process if a single commit message is
unparsable.
Instead we now log the issue and ignore the commit.

fix(parser): continue on unparsable commit message

---

internal/commitparser/conventionalcommits/conventionalcommits.go
internal/commitparser/conventionalcommits/conventionalcommits_test.go

GitLab generates commit messages of the pattern "scope: message\n" if no body is present. This throws up the conventional commits parser we use, and results in the error message "missing a blank line".
We now `strings.TrimSpace()` the commit message to avoid this problem.
Related to #4

fix(parser): invalid handling of title with new line

---

cmd/rp/cmd/run.go
internal/forge/gitlab/gitlab.go

Turns out that all we need is the path, and not the project id. The path is way more user friendly, and we can easily get it from a CI variable or combine it from the namespace & project name.
As GitLab support is unreleased, I will remove this commit from the Changelog:
```rp-commits
```

fix(gitlab): use project path wherever possible

---

.github/workflows/mirror.yaml

GitLab only considers repos on the current instance for its CI/CD catalog. We want to publish a GitLab CI/CD component for #4.

ci: push all changes to gitlab.com mirror

---

.ko.yaml

Images used in GitLab CI need to have a shell included, otherwise the job could not be started.
This replaces the default `cgr.dev/chainguard/static` base image with `cgr.dev/chainguard/busybox`. Busybox is the smallest image that includes a functional shell.
Needed for #55.

feat: add shell to container image

---

.gitlab-ci.yml
templates/run.yml

This adds a GitLab CI/CD component that can be `included` in users GitLab CI configuration to integrate releaser-pleaser.
Unlike the GitHub Action, this can not easily run whenever a merge request description is changed, only when changes are pushed to main.
Related to #4.

feat(gitlab): GitLab CI/CD component

---

internal/changelog/changelog.go
internal/changelog/changelog.md.tpl
internal/changelog/changelog_test.go
internal/commitparser/commitparser.go
releaserpleaser.go

The forge ui usually shows the release name right above the description, so this removes an unecessary duplicate bit of information.
In addition this also cleans up the changelog interface a bit and moves functionality where it belongs. Prepares a bit for custom changelogs in the future.
Closes #32

feat(changelog): omit version heading in forge release notes

---

.github/workflows/mirror.yaml

Job failed after adding new Git LFS files with the error:
```
Git LFS upload failed:
Uploading LFS objects:   0% (0/3), 0 B | 0 B/s, done.
(missing) docs/tutorials/gitlab-access-token.png (31b485bbe031443c4bfa0d39514dc7e5d524925aa877848def93ee40f69a1897)
(missing) docs/tutorials/gitlab-settings-merge-method.png (b853625854582a66ab2438f11e6001a88bcb276225abed536ba68617bde324db)
(missing) docs/tutorials/gitlab-settings-squash.png (0ce9b9826229851e961ef55d91cb9ba91ca9ca4d955a932d9ff6b10d04788c29)
hint: Your push was rejected due to missing or corrupt local objects.
hint: You can disable this check with: `git config lfs.allowincompletepush true`
error: failed to push some refs to 'https://gitlab.com/apricote/releaser-pleaser.git'
Error: Process completed with exit code 1.
```
Pulling the …

ci(mirror): fix missing lfs files on push

---

docs/tutorials/gitlab.md
internal/forge/gitlab/gitlab.go

Support self-managed gitlab instances by reading the GitLab CI environment variables.
Closes #63

feat(gitlab): support self-managed instances

---

internal/forge/gitlab/gitlab.go

When the release pull request was squashed on GitLab, the release creation fails with error
Error: failed to create pending releases: pull request is missing the merge commit
This fixes the problem by checking both `MergeCommitSHA` and `SquashCommitSHA` and using whichever is set.

fix(gitlab): release not created when release pr was squashed

---

.github/workflows/releaser-pleaser.yaml
action.yml

The current value caused the following error when running the action in a different repository:
Error: 'ghcr.io/apricote/releaser-pleaser:v0.4.1' should be either '[path]/Dockerfile' or 'docker://image[:tag]'.
Not sure why this did not come up before, as we are also using the same format for the CI in this repository, even if we use another tag.

fix(action): container image reference used wrong syntax

---

internal/commitparser/conventionalcommits/conventionalcommits.go
internal/commitparser/conventionalcommits/conventionalcommits_test.go

Fixes a bug where commits with messages that do not strictly conform to
conventional commits spec would be ignored. This could easily happen
while parsing footers like "Closes #xx" which would start the footer
section, while continuing with the body afterwards.
This solution has two downsides:
- these warnings are not surfaced to the user.
- If a `BREAKING CHANGE` footer exists after the parsing issue it is ignored
Thanks to @jooola for the bug report and test case.
Closes #99 #100

fix: use commits with slightly invalid messages in release notes

---

docs/reference/gitlab-cicd-component.md
templates/run.yml

In the CI/CD component, make the jobs `needs` setting configurable through an input and change the default to `[]`. This will cause the job to run immediately.

feat(gitlab): make job dependencies configurable and run immediately

---

internal/git/git.go
releaserpleaser.go

During a previous refactoring (#15) the Changelog generation logic stopped creating the file if it did not exist. This makes sure that the file actually gets created. This is primarily required while onboarding new repositories.
Closes #85

fix: create CHANGELOG.md if it does not exist

---

internal/versioning/semver.go
internal/versioning/semver_test.go
internal/versioning/versioning.go
releaserpleaser.go

In theory every forge can support this, but right now only GitHub allows one to define a release as "pre-release".
Closes #45

feat(github): mark pre-releases correctly

---

internal/forge/forge.go
internal/forge/github/github.go
internal/forge/gitlab/gitlab.go
internal/git/git.go
internal/git/git_test.go
releaserpleaser.go

Previously all commits were authored and committed by `releaser-pleaser <>`. This is weird when looking at the commit. We now check with the Forge API for details on the currently authenticated user, and use that name and email as the commit author. The commit committer stays the same for now.
In GitHub, the default `$GITHUB_TOKEN` does not allow access to the required endpoint, so for github the user `github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>` is hardcoded when the request fails.

feat: real user as commit author

---

.github/workflows/releaser-pleaser.yaml
docs/tutorials/github.md
templates/run.yml

Each run of releaser-pleaser acts on the same global state in the forge. Therefore, parallel runs are unnecessary.
This commit also communicates to the GitHub and GitLab CI pipelines that the releaser-pleaser jobs can be cancelled as early as possible.
- On GitHub Actions this can be guaranteed through the workflow settings. These settings are copied into each repository that uses releaser-pleaser, so users need to update this manually. I will add a note to the release notes for this.
- On GitLab CI/CD this requires the user to configure a project level setting to "auto-cancel redundant pipelines". We will not recommend user to set this, as it is quite invasive and can break their regular CI pipelines.

feat: run one job concurrently to reduce chance of conflicts

---

internal/forge/gitlab/gitlab.go

This changes allows detecting that the Release Pleaser PR is well merged. 
As of today, it fails with "2025-07-10T15:24:08Z ERR failed to create pending releases: pull request is missing the merge commit".
Failing job: https://gitlab.com/ccl-consulting/fleeting-plugin-scaleway/-/jobs/10639970620
Merged pull request: https://gitlab.com/ccl-consulting/fleeting-plugin-scaleway/-/merge_requests/12 
Merged pull request API view: https://gitlab.com/api/v4/projects/70582087/merge_requests/12
Landed commit: https://gitlab.com/ccl-consulting/fleeting-plugin-scaleway/-/commit/29ac598d0bf7952a85f28ac5cf5d3e113069f7ae

fix(gitlab): support Fast-forward merge

---

cmd/rp/cmd/root.go
cmd/rp/cmd/run.go
cmd/rp/main.go
internal/log/log.go

This enables us to create new commands for e2e tests.

refactor(cmd): use factories instead of global cobra command structs

---

.github/workflows/release.yaml
.github/workflows/releaser-pleaser.yaml

The `ko-build/setup-ko` action not only installed ko, but also configured `KO_DOCKER_REPO` and logged in using `ko login`.

ci: fix ko settings after using mise

---

docs/guides/release-notes.md
docs/reference/pr-options.md
internal/releasepr/releasepr_test.go
internal/testdata/changelog-content.txt
internal/testdata/changelog.txt
internal/testdata/description-no-overrides.txt
internal/testdata/description-overrides.txt
internal/testdata/description-prefix.txt
internal/testdata/description-suffix.txt
internal/testdata/prefix.txt
internal/testdata/suffix.txt
internal/testdata/testdata.go

Change the code blocks fences to 4 tildes for the release note prefix and suffix, to allow users to embed their own code blocks using back ticks.
Tildes as code block fences are supported by GFM: https://github.github.com/gfm/#fenced-code-blocks

feat: allow using code blocks within release-notes
